# Generated by Django 5.0.6 on 2024-06-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="formData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("no_of_family", models.PositiveIntegerField(default=0)),
                (
                    "raised_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fund_breakdown", models.TextField()),
                ("family_in_egypt", models.BooleanField(default=True)),
                ("fund_url", models.CharField(max_length=255)),
                ("comments", models.TextField()),
                ("approval", models.BooleanField(default=False)),
            ],
        ),
    ]
