# Generated by Django 5.0.6 on 2024-06-25 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0002_alter_formdata_approval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formdata",
            name="approval",
        ),
        migrations.CreateModel(
            name="approvedForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approval", models.BooleanField(default=False)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_form",
                        to="forms.formdata",
                    ),
                ),
            ],
        ),
    ]
