# Generated by Django 5.0.6 on 2024-06-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0003_remove_formdata_approval_approvedform"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdata",
            name="approval",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="approvedForm",
        ),
    ]
