# Generated by Django 5.0.6 on 2024-07-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_formdata_approval_delete_approvedform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='family_in_egypt',
            field=models.BooleanField(),
        ),
    ]
